package cn.lin037.nexus.application.explanation.enums;

import cn.lin037.nexus.common.constant.enums.result.ResultCodeEnum;
import lombok.Getter;

/**
 * 讲解模块错误码枚举
 *
 * @author LinSanQi
 */
@Getter
public enum ExplanationErrorCodeEnum implements ResultCodeEnum {

    // 讲解文档相关错误 (500xx)
    EXPLANATION_DOCUMENT_NOT_FOUND("EXPLANATION_50001", "讲解文档不存在"),
    EXPLANATION_DOCUMENT_CREATION_FAILED("EXPLANATION_50002", "讲解文档创建失败"),
    EXPLANATION_DOCUMENT_UPDATE_FAILED("EXPLANATION_50003", "讲解文档更新失败"),
    EXPLANATION_DOCUMENT_DELETE_FAILED("EXPLANATION_50004", "讲解文档删除失败"),
    EXPLANATION_DOCUMENT_STATUS_INVALID("EXPLANATION_50005", "讲解文档状态无效"),
    EXPLANATION_DOCUMENT_ACCESS_DENIED("EXPLANATION_50006", "无权限访问该讲解文档"),

    // 章节相关错误 (501xx)
    EXPLANATION_SECTION_NOT_FOUND("EXPLANATION_50101", "章节不存在"),
    EXPLANATION_SECTION_CREATION_FAILED("EXPLANATION_50102", "章节创建失败"),
    EXPLANATION_SECTION_UPDATE_FAILED("EXPLANATION_50103", "章节更新失败"),
    EXPLANATION_SECTION_DELETE_FAILED("EXPLANATION_50104", "章节删除失败"),
    EXPLANATION_SECTION_ORDER_INVALID("EXPLANATION_50105", "章节顺序无效"),
    EXPLANATION_SECTION_ACCESS_DENIED("EXPLANATION_50106", "无权限访问该章节"),

    // 小节相关错误 (502xx)
    EXPLANATION_SUBSECTION_NOT_FOUND("EXPLANATION_50201", "小节不存在"),
    EXPLANATION_SUBSECTION_CREATION_FAILED("EXPLANATION_50202", "小节创建失败"),
    EXPLANATION_SUBSECTION_UPDATE_FAILED("EXPLANATION_50203", "小节更新失败"),
    EXPLANATION_SUBSECTION_DELETE_FAILED("EXPLANATION_50204", "小节删除失败"),
    EXPLANATION_SUBSECTION_ORDER_INVALID("EXPLANATION_50205", "小节顺序无效"),
    EXPLANATION_SUBSECTION_ACCESS_DENIED("EXPLANATION_50206", "无权限访问该小节"),
    EXPLANATION_SUBSECTION_SECTION_MISMATCH("EXPLANATION_50207", "小节与章节不匹配"),

    // 知识点相关错误 (503xx)
    EXPLANATION_POINT_NOT_FOUND("EXPLANATION_50301", "讲解知识点不存在"),
    EXPLANATION_POINT_CREATION_FAILED("EXPLANATION_50302", "讲解知识点创建失败"),
    EXPLANATION_POINT_UPDATE_FAILED("EXPLANATION_50303", "讲解知识点更新失败"),
    EXPLANATION_POINT_DELETE_FAILED("EXPLANATION_50304", "讲解知识点删除失败"),
    EXPLANATION_POINT_ACCESS_DENIED("EXPLANATION_50305", "无权限访问该讲解知识点"),

    // 关系相关错误 (504xx)
    EXPLANATION_RELATION_NOT_FOUND("EXPLANATION_50401", "讲解关系不存在"),
    EXPLANATION_RELATION_CREATION_FAILED("EXPLANATION_50402", "讲解关系创建失败"),
    EXPLANATION_RELATION_UPDATE_FAILED("EXPLANATION_50403", "讲解关系更新失败"),
    EXPLANATION_RELATION_DELETE_FAILED("EXPLANATION_50404", "讲解关系删除失败"),
    EXPLANATION_RELATION_ACCESS_DENIED("EXPLANATION_50405", "无权限访问该讲解关系"),
    EXPLANATION_RELATION_POINTS_INVALID("EXPLANATION_50406", "关系的知识点无效"),

    // 位置调整相关错误 (505xx)
    POSITION_ADJUSTMENT_FAILED("EXPLANATION_50501", "位置调整失败"),
    POSITION_ORDER_INVALID("EXPLANATION_50502", "位置顺序无效"),
    POSITION_TARGET_NOT_FOUND("EXPLANATION_50503", "调整目标不存在"),
    POSITION_CIRCULAR_REFERENCE("EXPLANATION_50504", "位置调整存在循环引用"),

    // 批量操作相关错误 (506xx)
    BATCH_OPERATION_FAILED("EXPLANATION_50601", "批量操作失败"),
    BATCH_STYLE_UPDATE_FAILED("EXPLANATION_50602", "批量样式更新失败"),
    BATCH_DATA_INVALID("EXPLANATION_50603", "批量操作数据无效"),
    ;

    private final String code;
    private final String message;

    ExplanationErrorCodeEnum(String code, String message) {
        this.code = code;
        this.message = message;
    }
}